spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: manager
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update